### ISSUE TITLE
Last lists to load can't be folder

### ISSUE THREAD

**Issue by aguscha333** [NordMagnus/Trello-Folds#21] opened 2019-02-06 14:12 UTC
I have a trello with 17 lists or so. They take a bit of time to load. The ones that load right away get the cross icon to fold but the ones that load a bit later don't 
![image](https://user-images.githubusercontent.com/9297073/52347149-05f7c000-2a00-11e9-97e9-c130dda2d5e9.png)

also getting this error in console:
![image](https://user-images.githubusercontent.com/9297073/52347175-16a83600-2a00-11e9-904c-2c284ccbd3f6.png)

I've found that sometimes reloading helps but not always

**Comment by NordMagnus** [comment] 2019-02-16 19:07
@aguscha333 Can you please test with version 0.4 and check if anything changed. I can't reproduce it but not sure my test board is sufficient.

**Comment by aguscha333** [comment] 2019-02-20 23:12
@NordMagnus how do I do that, is it the latest available in the chrome web store or should I download it form here?

**Comment by NordMagnus** [comment] 2019-02-21 20:59
Just make sure you're updated in web store. Should be version **0.4**.

**Comment by NordMagnus** [comment] 2019-03-30 16:07
Also adding a "Refresh" button to new version if things are not formatted as expected when loading/reloading a board

**Comment by NordMagnus** [comment] 2019-08-18 21:08
Think this is fixed in 0.7 actually

**Closed by NordMagnus** 2019-08-18 21:08 UTC
Labels: bug
